const fs = require('fs');
const path = require('path');
process.chdir('d:\\睿谊的WPS\\Ferrariwork');

// Read novel text
const novel = fs.readFileSync('full_novel_text.txt', 'utf-8');

// Parse chapter vocab
const daily = fs.readFileSync('每日词汇对照表.txt', 'utf-8');

// Extract chapter words
const chapterWords = {};
let currentCh = 0;
for (const line of daily.split('\n')) {
  const m = line.match(/Chapter\s+(\d+)\s/);
  if (m) {
    currentCh = parseInt(m[1]);
    chapterWords[currentCh] = [];
  } else if (currentCh > 0) {
    const words = line.match(/\b([a-zA-Z]{3,})\b/g);
    if (words) chapterWords[currentCh].push(...words.map(w => w.toLowerCase()));
  }
}

// Build master word set
const stopWords = new Set(['the','and','for','are','was','not','its','but','our','has','had','can','may','all','one','two','use','new','old','etc','day','via','fit','sit','bit','yet','ago','nor','off','out','see','way','his','her','who','how','why','what','when','where','that','this','than','then','them','they','with','from','have','been','were','also','some','each','will','more','over','into','just','like','make','made','much','must','only','said','such','take','very','well','your','being','before','after','other','which','their','there','about','would','could','should','people','because','between','chapter','chapters']);
const masterSet = new Set();
for (const words of Object.values(chapterWords)) {
  for (const w of words) {
    if (!stopWords.has(w) && w.length >= 3) masterSet.add(w);
  }
}

// Add derived forms
const extra = [];
for (const w of masterSet) {
  if (w.length >= 4) {
    const suffixes = ['s','ed','ing','ly','ness','ment','tion','able','ible','ance','ence','ity','ive','ize','al'];
    for (const s of suffixes) {
      if (w.endsWith('e') && (s === 'ing' || s === 'ed')) extra.push(w.slice(0,-1) + s);
      extra.push(w + s);
    }
  }
}
for (const e of extra) masterSet.add(e);

console.log(`Master SAT words: ${masterSet.size}`);

// Split novel into chapters
const chPattern = /C\s*hapter\s*(\d+)\s*:/g;
const chMatches = [...novel.matchAll(chPattern)];
const chapters = {};
for (let i = 0; i < chMatches.length; i++) {
  const num = parseInt(chMatches[i][1]);
  const start = chMatches[i].index + chMatches[i][0].length;
  const end = i + 1 < chMatches.length ? chMatches[i+1].index : novel.length;
  chapters[num] = novel.substring(start, end);
}

// Build dictionary
const dict = {};
for (const w of masterSet) {
  if (w.length >= 3) dict[w] = {p:'',c:'',e:''};
}
fs.writeFileSync('merged_dict.json', JSON.stringify(dict), 'utf-8');
console.log(`Dictionary: ${Object.keys(dict).length} entries`);

// SAT definitions for common words
const defs = {
'intermittent':{p:'adj.',c:'间歇的；断断续续的',e:'occurring at irregular intervals'},
'observant':{p:'adj.',c:'善于观察的',e:'quick to notice things'},
'implicit':{p:'adj.',c:'含蓄的；隐含的',e:'implied though not plainly expressed'},
'discreet':{p:'adj.',c:'谨慎的',e:'careful and circumspect'},
'intrusive':{p:'adj.',c:'侵入的',e:'causing disruption or annoyance'},
'concise':{p:'adj.',c:'简洁的',e:'giving much information in few words'},
'compelling':{p:'adj.',c:'引人入胜的',e:'evoking interest powerfully'},
'deliberately':{p:'adv.',c:'故意地',e:'consciously and intentionally'},
'catalog':{p:'n.',c:'目录',e:'a complete list of items'},
'qualifying':{p:'adj.',c:'限定的',e:'modifying or limiting meaning'},
'tenuous':{p:'adj.',c:'脆弱的；站不住脚的',e:'very weak or slight'},
'permeable':{p:'adj.',c:'可渗透的',e:'allowing substances to pass through'},
'melancholy':{p:'adj.',c:'忧郁的',e:'a deep persistent sadness'},
'characteristic':{p:'adj.',c:'特有的；典型的',e:'typical of a particular person'},
'cherish':{p:'v.',c:'珍爱',e:'to hold dear'},
'redundant':{p:'adj.',c:'多余的',e:'no longer needed'},
'authentic':{p:'adj.',c:'真正的；真诚的',e:'genuine; real'},
'candor':{p:'n.',c:'坦率',e:'the quality of being open and honest'},
'embellish':{p:'v.',c:'装饰；润色',e:'to make more attractive by adding details'},
'profound':{p:'adj.',c:'深刻的',e:'very great or intense'},
'soothing':{p:'adj.',c:'抚慰的',e:'having a gently calming effect'},
'reprieve':{p:'n.',c:'暂缓',e:'a temporary relief'},
'elaborate':{p:'adj.',c:'精心制作的',e:'involving carefully arranged parts'},
'coalesced':{p:'v.',c:'合并',e:'came together to form one group'},
'captivated':{p:'adj.',c:'着迷的',e:'attracted and held by charm'},
'spontaneous':{p:'adj.',c:'自发的',e:'performed without external cause'},
'concerted':{p:'adj.',c:'协力',e:'jointly planned and determined'},
'tacitly':{p:'adv.',c:'默示地',e:'without being openly expressed'},
'disdain':{p:'n.',c:'蔑视',e:'feeling that someone is unworthy'},
'longing':{p:'n.',c:'渴望',e:'a yearning desire'},
'pretentious':{p:'adj.',c:'做作的',e:'attempting to impress by affecting importance'},
'frivolous':{p:'adj.',c:'轻浮的',e:'not having serious purpose'},
'perceptive':{p:'adj.',c:'敏锐的',e:'having sensitive insight'},
'scrutinize':{p:'v.',c:'仔细审视',e:'to examine closely'},
'periphery':{p:'n.',c:'边缘',e:'the outer limits of an area'},
'lingered':{p:'v.',c:'逗留',e:'stayed longer than necessary'},
'intricate':{p:'adj.',c:'错综复杂的',e:'very complicated or detailed'},
'immerse':{p:'v.',c:'沉浸',e:'to involve deeply'},
'vacant':{p:'adj.',c:'空的；茫然的',e:'empty; showing no thought'},
'articulate':{p:'adj.',c:'善于表达的',e:'having fluent clear speech'},
'innate':{p:'adj.',c:'先天的',e:'inborn; natural'},
'acquired':{p:'adj.',c:'后天习得的',e:'gained through experience'},
'ambivalence':{p:'n.',c:'矛盾心理',e:'mixed feelings'},
'nostalgia':{p:'n.',c:'怀旧',e:'sentimental longing for the past'},
'disillusion':{p:'n.',c:'幻灭',e:'disappointment from discovering truth'},
'fleeting':{p:'adj.',c:'短暂的',e:'lasting for a very short time'},
'affinity':{p:'n.',c:'亲密关系',e:'a natural liking for someone'},
'furtive':{p:'adj.',c:'鬼鬼祟祟的',e:'attempting to avoid notice'},
'discarded':{p:'adj.',c:'被抛弃的',e:'thrown away; rejected'},
'residual':{p:'adj.',c:'残留的',e:'remaining after the greater part is gone'},
'dissipated':{p:'adj.',c:'消散的',e:'dispersed; squandered'},
'anguish':{p:'n.',c:'极度痛苦',e:'severe mental or physical pain'},
'unobtrusive':{p:'adj.',c:'不引人注目的',e:'not conspicuous'},
'perpetually':{p:'adv.',c:'永久地',e:'in a way that never ends'},
'resonance':{p:'n.',c:'共鸣',e:'the quality of being deep and clear'},
'jarring':{p:'adj.',c:'刺耳的',e:'incongruous in a striking way'},
'mispronounced':{p:'v.',c:'发音错误',e:'pronounced incorrectly'},
'acquiesce':{p:'v.',c:'默许',e:'accept reluctantly without protest'},
'assert':{p:'v.',c:'断言',e:'to state a fact confidently'},
'negotiate':{p:'v.',c:'谈判',e:'to reach agreement through discussion'},
'collective':{p:'adj.',c:'集体的',e:'done by all members of a group'},
'saturated':{p:'adj.',c:'饱和的',e:'thoroughly soaked'},
'crescent':{p:'adj.',c:'新月形的',e:'shaped like a crescent moon'},
'exaggerate':{p:'v.',c:'夸张',e:'to represent as larger than reality'},
'perfunctory':{p:'adj.',c:'敷衍的',e:'carried out with minimum effort'},
'humility':{p:'n.',c:'谦逊',e:'a modest view of importance'},
'antidote':{p:'n.',c:'解药',e:'a remedy to counteract'},
'conceit':{p:'n.',c:'自负',e:'excessive pride in oneself'},
'reciprocate':{p:'v.',c:'回报',e:'to respond with similar action'},
'vulnerability':{p:'n.',c:'脆弱性',e:'the quality of being easily hurt'},
'inadequate':{p:'adj.',c:'不足的',e:'lacking the quality required'},
'inclination':{p:'n.',c:'倾向',e:'a natural tendency'},
'oscillating':{p:'adj.',c:'波动的',e:'moving back and forth'},
'startling':{p:'adj.',c:'令人震惊的',e:'very surprising'},
'dreading':{p:'v.',c:'恐惧',e:'anticipating with great fear'},
'anticipating':{p:'v.',c:'期待',e:'looking forward to'},
'disorienting':{p:'adj.',c:'让人迷失方向的',e:'causing loss of direction'},
'oblique':{p:'adj.',c:'间接的',e:'not straightforward'},
'conspicuous':{p:'adj.',c:'显眼的',e:'standing out clearly'},
'breach':{p:'v.',c:'打破',e:'to break through or violate'},
'discerned':{p:'v.',c:'辨别',e:'recognized or perceived'},
'disingenuous':{p:'adj.',c:'虚伪的',e:'not candid or sincere'},
'exaggerated':{p:'adj.',c:'夸张的',e:'represented as larger than true'},
'intriguing':{p:'adj.',c:'引人入胜的',e:'arousing curiosity'},
'enigmatic':{p:'adj.',c:'神秘的',e:'difficult to interpret'},
'stiffen':{p:'v.',c:'变僵硬',e:'to become rigid or tense'},
'insidious':{p:'adj.',c:'暗中为害的',e:'proceeding harmfully but subtly'},
'fascinating':{p:'adj.',c:'迷人的',e:'extremely interesting'},
'calculated':{p:'adj.',c:'精心策划的',e:'carefully planned'},
'adept':{p:'adj.',c:'擅长的',e:'very skilled'},
'manipulating':{p:'v.',c:'操纵',e:'handling skillfully'},
'projectiles':{p:'n.',c:'投射物',e:'objects thrown forward'},
'penetrate':{p:'v.',c:'穿透',e:'to go into or through'},
'tactics':{p:'n.',c:'策略',e:'carefully planned actions'},
'overt':{p:'adj.',c:'公开的',e:'done openly'},
'provoke':{p:'v.',c:'激怒',e:'to stir up a reaction'},
'precise':{p:'adj.',c:'精确的',e:'marked by exactness'},
'relevant':{p:'adj.',c:'相关的',e:'closely connected'},
'neutral':{p:'adj.',c:'中立的',e:'not supporting either side'},
'simulated':{p:'adj.',c:'模拟的',e:'imitated; pretended'},
'rumors':{p:'n.',c:'谣言',e:'unverified stories'},
'proliferate':{p:'v.',c:'扩散',e:'increase rapidly in number'},
'regulate':{p:'v.',c:'调节',e:'to control or maintain'},
'trembling':{p:'adj.',c:'颤抖的',e:'shaking involuntarily'},
'suppressed':{p:'adj.',c:'被压制的',e:'forcibly put an end to'},
'vulnerable':{p:'adj.',c:'易受伤的',e:'susceptible to harm'},
'exploited':{p:'adj.',c:'被利用的',e:'used unfairly'},
'adequately':{p:'adv.',c:'充分地',e:'to a satisfactory extent'},
'dominance':{p:'n.',c:'支配',e:'power over others'},
'specialty':{p:'n.',c:'专长',e:'area of expertise'},
'insecure':{p:'adj.',c:'不安全的',e:'not confident'},
'deflecting':{p:'v.',c:'转移',e:'causing to change direction'},
'deficiencies':{p:'n.',c:'缺陷',e:'failings; shortcomings'},
'appreciation':{p:'n.',c:'欣赏',e:'recognition of value'},
'insight':{p:'n.',c:'洞察力',e:'deep understanding'},
'incisive':{p:'adj.',c:'尖锐的',e:'intelligently analytical'},
'exasperating':{p:'adj.',c:'令人恼怒的',e:'intensely irritating'},
'reconfigured':{p:'adj.',c:'重新配置的',e:'arranged differently'},
'migrated':{p:'v.',c:'迁移',e:'moved from one place'},
'precipitated':{p:'v.',c:'促成',e:'caused suddenly'},
'obscure':{p:'adj.',c:'模糊的',e:'not clearly understood'},
'fragility':{p:'n.',c:'脆弱',e:'quality of being easily broken'},
'alliances':{p:'n.',c:'联盟',e:'unions for mutual benefit'},
'affiliations':{p:'n.',c:'从属关系',e:'connections with groups'},
'dissolve':{p:'v.',c:'溶解',e:'to end or disappear'},
'atrium':{p:'n.',c:'中庭',e:'a central open area'},
'expeditiously':{p:'adv.',c:'迅速地',e:'with speed and efficiency'},
'constrict':{p:'v.',c:'收缩',e:'to make narrower'},
'commodified':{p:'adj.',c:'商品化的',e:'turned into a commodity'},
'currency':{p:'n.',c:'货币',e:'money; general acceptance'},
'clinical':{p:'adj.',c:'冷静客观的',e:'coldly detached'},
'embellishment':{p:'n.',c:'装饰',e:'decorative detail'},
'malice':{p:'n.',c:'恶意',e:'desire to harm'},
'symptom':{p:'n.',c:'症状',e:'indication of a condition'},
'spectacles':{p:'n.',c:'景象',e:'visually striking displays'},
'manifestation':{p:'n.',c:'表现',e:'clear showing of something'},
'narrowing':{p:'adj.',c:'变窄的',e:'becoming more limited'},
'transparency':{p:'n.',c:'透明',e:'openness; clarity'},
'liability':{p:'n.',c:'责任',e:'a thing that causes problems'},
'secrecy':{p:'n.',c:'保密',e:'keeping things secret'},
'commodity':{p:'n.',c:'商品',e:'a product that can be traded'},
'suspect':{p:'adj.',c:'可疑的',e:'not to be trusted'},
'opaque':{p:'adj.',c:'不透明的',e:'not transparent'},
'threatening':{p:'adj.',c:'威胁的',e:'having hostile intent'},
'labyrinth':{p:'n.',c:'迷宫',e:'a complex network of paths'},
'obligations':{p:'n.',c:'义务',e:'duties; commitments'},
'honest':{p:'adj.',c:'诚实的',e:'free of deceit'},
'respite':{p:'n.',c:'缓解',e:'a short rest period'},
'translucent':{p:'adj.',c:'半透明的',e:'partially transparent'},
'peripheral':{p:'adj.',c:'外围的',e:'on the edge; marginal'},
'coveted':{p:'adj.',c:'令人垂涎的',e:'greatly desired'},
'disruption':{p:'n.',c:'中断',e:'disturbance of normal function'},
'complicated':{p:'adj.',c:'复杂的',e:'consisting of many parts'},
'ambiguous':{p:'adj.',c:'模棱两可的',e:'open to interpretation'},
'amicably':{p:'adv.',c:'友善地',e:'in a friendly manner'},
'candid':{p:'adj.',c:'坦率的',e:'truthful and straightforward'},
'inflict':{p:'v.',c:'施加',e:'to cause to be suffered'},
'clandestine':{p:'adj.',c:'秘密的',e:'kept secret'},
'ignite':{p:'v.',c:'点燃',e:'to catch fire; to arouse'},
'disconcerting':{p:'adj.',c:'令人不安的',e:'causing unease'},
'contradicted':{p:'v.',c:'矛盾',e:'asserted the opposite'},
'impromptu':{p:'adj.',c:'即兴的',e:'done without preparation'},
'scrutinizing':{p:'v.',c:'仔细审视',e:'examining closely'},
'elusive':{p:'adj.',c:'难以捉摸的',e:'difficult to find'},
'precision':{p:'n.',c:'精确',e:'exactness'},
'convened':{p:'v.',c:'召集',e:'came together for meeting'},
'drifting':{p:'adj.',c:'漂流的',e:'moving without direction'},
'unresolved':{p:'adj.',c:'未解决的',e:'not settled'},
'bulletin':{p:'n.',c:'公告',e:'official statement'},
'proximity':{p:'n.',c:'接近',e:'nearness in space'},
'deliberate':{p:'adj.',c:'故意的',e:'intentional; careful'},
'anticipation':{p:'n.',c:'期待',e:'looking forward to'},
'wariness':{p:'n.',c:'警惕',e:'caution about dangers'},
'incision':{p:'n.',c:'切口',e:'a sharp cut'},
'impeccable':{p:'adj.',c:'无懈可击的',e:'faultless'},
'defensive':{p:'adj.',c:'防御的',e:'intended to protect'},
'confessional':{p:'adj.',c:'自白的',e:'admitting private truths'},
'evocative':{p:'adj.',c:'唤起记忆的',e:'bringing strong memories'},
'superfluous':{p:'adj.',c:'多余的',e:'more than needed'},
'initiated':{p:'v.',c:'开始',e:'started; set in motion'},
'legitimate':{p:'adj.',c:'合法的',e:'conforming to rules'},
'disquieting':{p:'adj.',c:'令人不安的',e:'causing anxiety'},
'miscalculated':{p:'v.',c:'误算',e:'calculated incorrectly'},
'assessing':{p:'v.',c:'评估',e:'evaluating'},
'sincerity':{p:'n.',c:'真诚',e:'genuineness'},
'context':{p:'n.',c:'上下文',e:'surrounding circumstances'},
'tangle':{p:'n.',c:'纠缠',e:'confused mass'},
'disentangle':{p:'v.',c:'解开',e:'free from complications'},
'discomfiting':{p:'adj.',c:'令人不安的',e:'making uneasy'},
'indispensable':{p:'adj.',c:'不可或缺的',e:'absolutely necessary'},
'retrospective':{p:'adj.',c:'回顾的',e:'looking back'},
'uncomfortable':{p:'adj.',c:'不舒服的',e:'causing discomfort'},
'fundamental':{p:'adj.',c:'基本的',e:'forming the base'},
'capacity':{p:'n.',c:'能力',e:'ability; maximum amount'},
'incessant':{p:'adj.',c:'不断的',e:'without pause'},
'dissected':{p:'adj.',c:'分析的',e:'cut apart; analyzed'},
'reassembled':{p:'adj.',c:'重新组装的',e:'put back together'},
'scrutinized':{p:'adj.',c:'被仔细检查的',e:'examined closely'},
'meticulous':{p:'adj.',c:'一丝不苟的',e:'very careful and precise'},
'obsessive':{p:'adj.',c:'着迷的',e:'excessively preoccupied'},
'depleted':{p:'adj.',c:'耗尽的',e:'reduced; exhausted'},
'exhausted':{p:'adj.',c:'筋疲力尽的',e:'drained of energy'},
'evasive':{p:'adj.',c:'回避的',e:'tending to avoid'},
'moderation':{p:'n.',c:'适度',e:'avoidance of excess'},
'neglect':{p:'n.',c:'忽视',e:'failure to care for'},
'contemplating':{p:'v.',c:'沉思',e:'thinking deeply about'},
'temperamental':{p:'adj.',c:'喜怒无常的',e:'moody; volatile'},
'vigilance':{p:'n.',c:'警惕',e:'watchfulness'},
'restraint':{p:'n.',c:'克制',e:'self-control'},
'perilous':{p:'adj.',c:'危险的',e:'full of danger'},
'ledge':{p:'n.',c:'岩架',e:'narrow shelf'},
'perfection':{p:'n.',c:'完美',e:'state of being flawless'},
'tyrannical':{p:'adj.',c:'暴虐的',e:'cruelly oppressive'},
'uncharacteristic':{p:'adj.',c:'不典型的',e:'not typical'},
'pragmatic':{p:'adj.',c:'实用的',e:'practical'},
'prickle':{p:'n.',c:'刺痛感',e:'tingling sensation'},
'softened':{p:'adj.',c:'变柔和的',e:'made less harsh'},
'cavernous':{p:'adj.',c:'洞穴般的',e:'like a cavern'},
'podium':{p:'n.',c:'讲台',e:'raised platform'},
'hammering':{p:'n.',c:'锤击',e:'forceful pounding'},
'blinding':{p:'adj.',c:'刺眼的',e:'so bright it blinds'},
'steady':{p:'adj.',c:'稳定的',e:'firmly fixed'},
'constricting':{p:'adj.',c:'收缩的',e:'causing tightness'},
'abbreviated':{p:'adj.',c:'简短的',e:'shortened'},
'flawless':{p:'adj.',c:'完美无瑕的',e:'without flaws'},
'reciting':{p:'v.',c:'背诵',e:'reading aloud from memory'},
'palpable':{p:'adj.',c:'明显的',e:'able to be touched or felt'},
'excruciating':{p:'adj.',c:'极痛苦的',e:'intensely painful'},
'discomfiture':{p:'n.',c:'尴尬',e:'unease; embarrassment'},
'audible':{p:'adj.',c:'听得见的',e:'able to be heard'},
'controlled':{p:'adj.',c:'克制的',e:'restrained'},
'imposter':{p:'n.',c:'冒名顶替者',e:'pretender; fraud'},
'exposed':{p:'adj.',c:'暴露的',e:'left unprotected'},
'compulsion':{p:'n.',c:'强迫',e:'irresistible urge'},
'authenticity':{p:'n.',c:'真实性',e:'quality of being genuine'},
'exhausting':{p:'adj.',c:'令人疲惫的',e:'very tiring'},
'endeavor':{p:'n.',c:'努力',e:'determined effort'},
'curating':{p:'v.',c:'精心挑选',e:'selecting carefully'},
'stronger':{p:'adj.',c:'更强的',e:'more powerful'},
'internalize':{p:'v.',c:'内化',e:'make part of oneself'},
'scrutiny':{p:'n.',c:'仔细审查',e:'close examination'},
'harshest':{p:'adj.',c:'最严厉的',e:'most severe'},
'relentless':{p:'adj.',c:'无情的',e:'unceasingly intense'},
'prosecutors':{p:'n.',c:'检察官',e:'legal accusers'},
'irony':{p:'n.',c:'讽刺',e:'contrary outcome'},
'condemning':{p:'v.',c:'谴责',e:'expressing disapproval'},
'simulating':{p:'v.',c:'假装',e:'imitating'},
'intruders':{p:'n.',c:'入侵者',e:'unwelcome entrants'},
'profoundly':{p:'adv.',c:'深刻地',e:'deeply'},
'recognition':{p:'n.',c:'认可',e:'acknowledgment'},
'curated':{p:'adj.',c:'精心挑选的',e:'carefully selected'},
'perfected':{p:'adj.',c:'完美的',e:'made flawless'},
'uncertain':{p:'adj.',c:'不确定的',e:'not sure'},
'genuine':{p:'adj.',c:'真正的',e:'authentic; sincere'},
'subdued':{p:'adj.',c:'柔和的',e:'quiet; restrained'},
'sincere':{p:'adj.',c:'真诚的',e:'honest; genuine'},
'expand':{p:'v.',c:'扩展',e:'become larger'},
'relief':{p:'n.',c:'缓解',e:'alleviation; ease'},
'rejected':{p:'adj.',c:'被拒绝的',e:'dismissed'},
'imperfect':{p:'adj.',c:'不完美的',e:'not perfect'},
'accepted':{p:'adj.',c:'被接受的',e:'generally approved'},
'extraordinary':{p:'adj.',c:'非凡的',e:'very unusual'},
'complex':{p:'adj.',c:'复杂的',e:'complicated; intricate'},
'guarded':{p:'adj.',c:'谨慎的',e:'cautious; reserved'},
'obligation':{p:'n.',c:'义务',e:'duty; commitment'},
'tentative':{p:'adj.',c:'试探性的',e:'uncertain; hesitant'},
'notification':{p:'n.',c:'通知',e:'act of informing'},
'evasion':{p:'n.',c:'逃避',e:'act of avoiding'},
'conspicuously':{p:'adv.',c:'显眼地',e:'in a noticeable way'},
'posture':{p:'n.',c:'姿态',e:'body position; attitude'},
'unmistakable':{p:'adj.',c:'不会错的',e:'clearly identifiable'},
'intervention':{p:'n.',c:'干预',e:'act of intervening'},
'measured':{p:'adj.',c:'有分寸的',e:'carefully considered'},
'undercurrent':{p:'n.',c:'暗流',e:'underlying feeling'},
'concern':{p:'n.',c:'担忧',e:'worry; care'},
'evaluation':{p:'n.',c:'评估',e:'assessment'},
'activate':{p:'v.',c:'激活',e:'make active'},
'instinctive':{p:'adj.',c:'本能的',e:'based on instinct'},
'fortification':{p:'n.',c:'防御工事',e:'defensive structure'},
'inscrutable':{p:'adj.',c:'难以理解的',e:'impossible to understand'},
'anxiety':{p:'n.',c:'焦虑',e:'worry; unease'},
'prudent':{p:'adj.',c:'谨慎的',e:'acting with care'},
'distracted':{p:'adj.',c:'分心的',e:'unable to concentrate'},
'unyielding':{p:'adj.',c:'不屈的',e:'firm; inflexible'},
'overwhelming':{p:'adj.',c:'压倒性的',e:'very intense'},
'derail':{p:'v.',c:'阻挠',e:'obstruct; divert'},
'entanglements':{p:'n.',c:'纠缠',e:'complicated relationships'},
'diminishment':{p:'n.',c:'减少',e:'reduction; belittlement'},
'mutual':{p:'adj.',c:'相互的',e:'shared; reciprocal'},
'precarious':{p:'adj.',c:'不稳定的',e:'uncertain; risky'},
'indignation':{p:'n.',c:'愤慨',e:'anger at injustice'},
'conviction':{p:'n.',c:'信念',e:'firm belief'},
'critical':{p:'adj.',c:'关键的',e:'crucial; disapproving'},
'juncture':{p:'n.',c:'关键时刻',e:'critical point'},
'consequential':{p:'adj.',c:'重要的',e:'resulting; important'},
'sanction':{p:'v.',c:'批准',e:'authorize; penalize'},
'jeopardize':{p:'v.',c:'危及',e:'put at risk'},
'liberation':{p:'n.',c:'解放',e:'act of freeing'},
'futility':{p:'n.',c:'徒劳',e:'pointlessness'},
'perpetual':{p:'adj.',c:'永久的',e:'never ending'},
'constricted':{p:'adj.',c:'受限制的',e:'tight; restricted'},
'advise':{p:'v.',c:'建议',e:'offer suggestions'},
'retrospectively':{p:'adv.',c:'回顾地',e:'looking back'},
'regret':{p:'n.',c:'后悔',e:'sadness about past'},
'dissonance':{p:'n.',c:'不协调',e:'lack of harmony'},
'stability':{p:'n.',c:'稳定',e:'state of being stable'},
'turbulence':{p:'n.',c:'动荡',e:'disorder; unrest'},
'unassuming':{p:'adj.',c:'谦逊的',e:'modest'},
'profundity':{p:'n.',c:'深度',e:'great depth'},
'collaborate':{p:'v.',c:'合作',e:'work together'},
'turbulent':{p:'adj.',c:'混乱的',e:'disorderly'},
'convergence':{p:'n.',c:'汇聚',e:'coming together'},
'erratic':{p:'adj.',c:'不稳定的',e:'irregular; unpredictable'},
'ribbon':{p:'n.',c:'丝带',e:'narrow strip of fabric'},
'minuscule':{p:'adj.',c:'极小的',e:'extremely small'},
'faded':{p:'adj.',c:'褪色的',e:'lost color or vigor'},
'shift':{p:'n.',c:'转变',e:'change; move'},
'unspoken':{p:'adj.',c:'未说出口的',e:'not expressed in words'},
'truce':{p:'n.',c:'休战',e:'temporary peace'},
'relics':{p:'n.',c:'遗物',e:'surviving objects'},
'semicircle':{p:'n.',c:'半圆',e:'half circle'},
'calibrated':{p:'adj.',c:'校准过的',e:'carefully adjusted'},
'engrossed':{p:'adj.',c:'全神贯注的',e:'fully absorbed'},
'grazing':{p:'adj.',c:'轻擦的',e:'touching lightly'},
'understated':{p:'adj.',c:'低调的',e:'subtle; restrained'},
'reassuring':{p:'adj.',c:'令人安心的',e:'comforting'},
'characteristically':{p:'adv.',c:'典型地',e:'typically'},
'recede':{p:'v.',c:'后退',e:'move back; diminish'},
'unremarkable':{p:'adj.',c:'平凡的',e:'ordinary'},
'derivative':{p:'adj.',c:'模仿他人的',e:'imitative'},
'commendable':{p:'adj.',c:'值得赞扬的',e:'praiseworthy'},
'shifted':{p:'v.',c:'转变了',e:'changed position'},
'perceptibly':{p:'adv.',c:'可察觉地',e:'noticeably'},
'polished':{p:'adj.',c:'优雅的',e:'refined; sophisticated'},
'assurance':{p:'n.',c:'自信',e:'confidence; guarantee'},
'reluctant':{p:'adj.',c:'不情愿的',e:'unwilling'},
'interminable':{p:'adj.',c:'无休止的',e:'endless'},
'obliterated':{p:'adj.',c:'被消灭的',e:'destroyed completely'},
'terrifying':{p:'adj.',c:'令人恐惧的',e:'causing extreme fear'},
'impulse':{p:'n.',c:'冲动',e:'sudden urge'},
'retreat':{p:'v.',c:'撤退',e:'withdraw; pull back'},
'abbreviate':{p:'v.',c:'缩写',e:'shorten; reduce'},
'formulaic':{p:'adj.',c:'公式化的',e:'produced by formula'},
'solidarity':{p:'n.',c:'团结',e:'unity; mutual support'},
'unfailing':{p:'adj.',c:'始终如一的',e:'constant; reliable'},
'fraudulent':{p:'adj.',c:'欺诈的',e:'deceitful; fake'},
'exhaustion':{p:'n.',c:'疲惫',e:'extreme tiredness'},
'loneliness':{p:'n.',c:'孤独',e:'sadness of being alone'},
'concealing':{p:'v.',c:'隐藏',e:'hiding; keeping secret'},
'paradox':{p:'n.',c:'悖论',e:'seeming contradiction'},
'disposable':{p:'adj.',c:'可抛弃的',e:'easily discarded'},
'antithesis':{p:'n.',c:'对立面',e:'direct opposite'},
'prerequisite':{p:'n.',c:'先决条件',e:'required condition'},
'connection':{p:'n.',c:'联系',e:'link; relationship'},
'becoming':{p:'adj.',c:'合适的',e:'suitable; developing'},
'threshold':{p:'n.',c:'门槛',e:'point of entry; limit'},
'suspended':{p:'adj.',c:'暂停的',e:'temporarily stopped'},
'sustained':{p:'adj.',c:'持续的',e:'continuing for long'},
'exhilarating':{p:'adj.',c:'令人兴奋的',e:'thrilling; exciting'},
'annihilated':{p:'adj.',c:'被消灭的',e:'destroyed completely'},
'admiration':{p:'n.',c:'钦佩',e:'respect; approval'},
'contrition':{p:'n.',c:'忏悔',e:'remorse; penitence'},
'composure':{p:'n.',c:'镇定',e:'calmness'},
'grandiose':{p:'adj.',c:'宏伟的',e:'impressive but pretentious'},
'theatrical':{p:'adj.',c:'戏剧性的',e:'exaggerated; dramatic'},
'grappling':{p:'v.',c:'努力应对',e:'struggling with'},
'definitive':{p:'adj.',c:'决定性的',e:'conclusive; authoritative'},
'reduced':{p:'adj.',c:'减少的',e:'made smaller'},
'superficial':{p:'adj.',c:'表面的',e:'surface-level; shallow'},
'assimilate':{p:'v.',c:'同化',e:'absorb; integrate'},
'integrating':{p:'v.',c:'整合',e:'combining into whole'},
'invisibility':{p:'n.',c:'隐形',e:'state of being unseen'},
'lonely':{p:'adj.',c:'孤独的',e:'feeling alone'},
'reverse':{p:'adj.',c:'相反的',e:'opposite direction'},
'displacement':{p:'n.',c:'移位',e:'being moved from place'},
'indelibly':{p:'adv.',c:'不可磨灭地',e:'permanently; inerasably'},
'fluent':{p:'adj.',c:'流利的',e:'able to speak easily'},
'adaptation':{p:'n.',c:'适应',e:'adjustment to conditions'},
'calibrate':{p:'v.',c:'校准',e:'adjust precisely'},
'accommodated':{p:'v.',c:'适应',e:'adjusted to fit'},
'dispersing':{p:'v.',c:'分散',e:'scattering; spreading'},
'fragmented':{p:'adj.',c:'支离破碎的',e:'broken into pieces'},
'charismatic':{p:'adj.',c:'有魅力的',e:'compellingly charming'},
'resonated':{p:'v.',c:'引起共鸣',e:'evoked shared feeling'},
'dilemma':{p:'n.',c:'困境',e:'difficult choice'},
'universal':{p:'adj.',c:'普遍的',e:'applying to all'},
'cohesive':{p:'adj.',c:'有凝聚力的',e:'unified; sticking together'},
'interior':{p:'n.',c:'内部',e:'inner part; inside'},
'exterior':{p:'n.',c:'外部',e:'outer surface'},
'isolation':{p:'n.',c:'隔离',e:'being alone; separation'},
'opposition':{p:'n.',c:'反对',e:'resistance; contrast'},
'static':{p:'adj.',c:'静态的',e:'unchanging; fixed'},
'dynamic':{p:'adj.',c:'动态的',e:'constantly changing'},
'monolith':{p:'n.',c:'巨石',e:'massive uniform structure'},
'mosaic':{p:'n.',c:'马赛克',e:'picture of small pieces'},
'proclaim':{p:'v.',c:'宣布',e:'announce officially'},
'resounding':{p:'adj.',c:'响亮的',e:'emphatic; echoing'},
'seismic':{p:'adj.',c:'重大的',e:'enormous in impact'},
'surreal':{p:'adj.',c:'超现实的',e:'bizarre; dreamlike'},
'parameters':{p:'n.',c:'参数',e:'boundaries; limits'},
'subtly':{p:'adv.',c:'微妙地',e:'delicately; slightly'},
'recalibrated':{p:'adj.',c:'重新校准的',e:'readjusted'},
'significant':{p:'adj.',c:'重要的',e:'important; noteworthy'},
'impersonating':{p:'v.',c:'冒充',e:'pretending to be another'},
'conceal':{p:'v.',c:'隐藏',e:'hide; keep secret'},
'vulnerabilities':{p:'n.',c:'脆弱性',e:'weaknesses'},
'intact':{p:'adj.',c:'完好无损的',e:'undamaged; whole'},
'voicemail':{p:'n.',c:'语音信箱',e:'voice message system'},
'defiance':{p:'n.',c:'违抗',e:'open resistance'},
'liberating':{p:'adj.',c:'解放的',e:'freeing; empowering'},
'guilty':{p:'adj.',c:'内疚的',e:'feeling remorse'},
'governing':{p:'adj.',c:'统治的',e:'controlling; ruling'},
'equanimity':{p:'n.',c:'平静',e:'calmness; composure'},
'admirable':{p:'adj.',c:'令人钦佩的',e:'deserving admiration'},
'bridge':{p:'n.',c:'桥梁',e:'connection; link'},
'battleground':{p:'n.',c:'战场',e:'arena of conflict'},
'contest':{p:'n.',c:'比赛',e:'competition; struggle'},
'autonomy':{p:'n.',c:'自主权',e:'self-governance'},
'adversarial':{p:'adj.',c:'对抗的',e:'confrontational'},
'alienating':{p:'adj.',c:'疏远的',e:'causing isolation'},
'atmosphere':{p:'n.',c:'气氛',e:'mood; tone'},
'charged':{p:'adj.',c:'充满情绪的',e:'filled with tension'},
'hostile':{p:'adj.',c:'敌对的',e:'unfriendly; antagonistic'},
'integrity':{p:'n.',c:'正直',e:'moral uprightness'},
'confinement':{p:'n.',c:'限制',e:'being restricted'},
'imperceptibly':{p:'adv.',c:'察觉不到地',e:'unnoticeably'},
'resolution':{p:'n.',c:'决心',e:'firm decision'},
'fragile':{p:'adj.',c:'易碎的',e:'easily broken'},
'plummet':{p:'v.',c:'暴跌',e:'fall rapidly'},
'cascading':{p:'adj.',c:'瀑布般落下的',e:'falling in cascade'},
'ecosystem':{p:'n.',c:'生态系统',e:'biological community'},
'seasonal':{p:'adj.',c:'季节性的',e:'relating to seasons'},
'undisputed':{p:'adj.',c:'无可争议的',e:'not questioned'},
'arbiters':{p:'n.',c:'仲裁者',e:'judges; authorities'},
'cachet':{p:'n.',c:'声望',e:'prestige; status'},
'fragment':{p:'n.',c:'碎片',e:'broken piece'},
'defected':{p:'v.',c:'叛逃',e:'abandoned allegiance'},
'ostensibly':{p:'adv.',c:'表面上',e:'apparently'},
'covertly':{p:'adv.',c:'秘密地',e:'secretly'},
'excluded':{p:'adj.',c:'被排除的',e:'kept out'},
'coalition':{p:'n.',c:'联盟',e:'alliance; union'},
'agonized':{p:'adj.',c:'极度痛苦的',e:'suffering greatly'},
'dynamics':{p:'n.',c:'互动方式',e:'forces of change'},
'urgent':{p:'adj.',c:'紧急的',e:'requiring immediate action'},
'sustaining':{p:'adj.',c:'维持的',e:'supporting; nourishing'},
'struggling':{p:'adj.',c:'挣扎的',e:'making great effort'},
'firmness':{p:'n.',c:'坚定',e:'steadiness; resolve'},
'confidence':{p:'n.',c:'自信',e:'self-assurance'},
'emerging':{p:'adj.',c:'新兴的',e:'coming into view'},
'transform':{p:'v.',c:'转变',e:'change dramatically'},
'transformed':{p:'adj.',c:'转变的',e:'changed completely'},
'transformation':{p:'n.',c:'变革',e:'dramatic change'},
'subtle':{p:'adj.',c:'微妙的',e:'delicate; understated'},
'diligent':{p:'adj.',c:'勤奋的',e:'hardworking'},
'steadier':{p:'adj.',c:'更稳定的',e:'more stable'},
'terrified':{p:'adj.',c:'极度恐惧的',e:'extremely frightened'},
'thesis':{p:'n.',c:'论点',e:'central argument'},
'performative':{p:'adj.',c:'表演性的',e:'done for show'},
'enthusiasm':{p:'n.',c:'热情',e:'intense enjoyment'},
'consistency':{p:'n.',c:'一致性',e:'uniformity; reliability'},
'unusually':{p:'adv.',c:'异常地',e:'atypically'},
'considerate':{p:'adj.',c:'体贴的',e:'thoughtful of others'},
'mature':{p:'adj.',c:'成熟的',e:'fully developed; wise'},
'avoiding':{p:'v.',c:'避免',e:'keeping away from'},
'discomfort':{p:'n.',c:'不适',e:'unease; slight pain'},
'communicating':{p:'v.',c:'沟通',e:'sharing information'},
'coasting':{p:'v.',c:'滑行',e:'moving without effort'},
'softening':{p:'adj.',c:'温和化的',e:'becoming less harsh'},
'resentment':{p:'n.',c:'怨恨',e:'bitter indignation'},
'stinging':{p:'adj.',c:'刺痛的',e:'causing sharp pain'},
'contemplative':{p:'adj.',c:'沉思的',e:'deeply thoughtful'},
'permeated':{p:'v.',c:'渗透',e:'spread throughout'},
'annotated':{p:'adj.',c:'有注释的',e:'with explanatory notes'},
'indifferent':{p:'adj.',c:'漠不关心的',e:'having no interest'},
'concentrated':{p:'adj.',c:'集中的',e:'focused intensely'},
'focus':{p:'n.',c:'焦点',e:'center of attention'},
'validation':{p:'n.',c:'验证',e:'confirmation; approval'},
'demonstrate':{p:'v.',c:'展示',e:'show clearly'},
'accuse':{p:'v.',c:'指责',e:'charge with fault'},
'inadequacy':{p:'n.',c:'不足',e:'insufficiency'},
'intrinsic':{p:'adj.',c:'内在的',e:'inherent; essential'},
'curiosity':{p:'n.',c:'好奇心',e:'desire to know'},
'unorthodox':{p:'adj.',c:'非传统的',e:'unconventional'},
'conventional':{p:'adj.',c:'传统的',e:'traditional; normal'},
'trajectory':{p:'n.',c:'发展轨迹',e:'path; course'},
'evolving':{p:'adj.',c:'发展的',e:'developing gradually'},
'miserable':{p:'adj.',c:'痛苦的',e:'very unhappy'},
'criticized':{p:'v.',c:'批评',e:'found fault with'},
'accurate':{p:'adj.',c:'准确的',e:'correct; exact'},
'gradual':{p:'adj.',c:'逐渐的',e:'happening slowly'},
'defenses':{p:'n.',c:'防御',e:'protective measures'},
'constructed':{p:'adj.',c:'建造的',e:'built; assembled'},
'softer':{p:'adj.',c:'更温和的',e:'gentler; less harsh'},
'receptive':{p:'adj.',c:'乐于接受的',e:'open to new ideas'},
'dimension':{p:'n.',c:'方面',e:'aspect; facet'},
'bereavement':{p:'n.',c:'丧亲之痛',e:'loss of loved one'},
'adequate':{p:'adj.',c:'足够的',e:'sufficient; suitable'},
'wistful':{p:'adj.',c:'惆怅的',e:'yearning; melancholy'},
'epiphany':{p:'n.',c:'顿悟',e:'sudden realization'},
'inevitable':{p:'adj.',c:'不可避免的',e:'unavoidable'},
'encourage':{p:'v.',c:'鼓励',e:'give support to'},
'adjusted':{p:'adj.',c:'适应了的',e:'adapted; modified'},
'affixed':{p:'adj.',c:'附上的',e:'attached firmly'},
'frenetic':{p:'adj.',c:'狂热的',e:'fast and energetic'},
'negotiations':{p:'n.',c:'谈判',e:'formal discussions'},
'tumultuous':{p:'adj.',c:'喧嚣的',e:'disorderly; turbulent'},
'congregate':{p:'v.',c:'聚集',e:'gather together'},
'amused':{p:'adj.',c:'被逗乐的',e:'entertained'},
'detachment':{p:'n.',c:'超脱',e:'emotional distance'},
'inherently':{p:'adv.',c:'内在地',e:'by its very nature'},
'meaningless':{p:'adj.',c:'无意义的',e:'without meaning'},
'arbitrary':{p:'adj.',c:'任意的',e:'random; based on whim'},
'agonize':{p:'v.',c:'苦苦思索',e:'suffer mental distress'},
'transaction':{p:'n.',c:'交易',e:'exchange; deal'},
'current':{p:'adj.',c:'当前的',e:'present; in circulation'},
'sustainable':{p:'adj.',c:'可持续的',e:'able to be maintained'},
'archived':{p:'adj.',c:'已存档的',e:'stored in archive'},
'gratifying':{p:'adj.',c:'令人满足的',e:'pleasing; satisfying'},
'flattering':{p:'adj.',c:'讨好的',e:'pleasing to ego'},
'unexpected':{p:'adj.',c:'意外的',e:'not anticipated'},
'blush':{p:'v.',c:'脸红',e:'turn red from embarrassment'},
'physiological':{p:'adj.',c:'生理的',e:'relating to body functions'},
'anonymity':{p:'n.',c:'匿名',e:'state of being unknown'},
'denuded':{p:'adj.',c:'裸露的',e:'stripped bare'},
'significance':{p:'n.',c:'重要性',e:'importance; meaning'},
'conferred':{p:'v.',c:'授予',e:'granted; bestowed'},
'unreadable':{p:'adj.',c:'难以辨认的',e:'impossible to read'},
'tangible':{p:'adj.',c:'有形的',e:'real; touchable'},
'artifact':{p:'n.',c:'人工制品',e:'human-made object'},
'precious':{p:'adj.',c:'珍贵的',e:'of great value'},
'slanting':{p:'adj.',c:'倾斜的',e:'at an angle'},
'replete':{p:'adj.',c:'充满的',e:'filled; abundant'},
'slanted':{p:'adj.',c:'有倾向性的',e:'biased; angled'},
'elliptical':{p:'adj.',c:'省略的',e:'deliberately obscure'},
'allusive':{p:'adj.',c:'暗指的',e:'full of indirect references'},
'imagery':{p:'n.',c:'意象',e:'descriptive language'},
'hovered':{p:'v.',c:'徘徊',e:'remained floating'},
'obscurity':{p:'n.',c:'模糊',e:'state of being unknown'},
'revelation':{p:'n.',c:'揭露',e:'surprising disclosure'},
'arrested':{p:'v.',c:'吸引',e:'captured attention; stopped'},
'incongruities':{p:'n.',c:'不协调',e:'inconsistencies'},
'smooth':{p:'v.',c:'消除',e:'make even; remove difficulties'},
'collage':{p:'n.',c:'拼贴画',e:'collection of diverse elements'},
'contradictory':{p:'adj.',c:'矛盾的',e:'mutually opposed'},
'brittle':{p:'adj.',c:'脆弱的',e:'hard but easily broken'},
'catalyzed':{p:'v.',c:'催化',e:'accelerated; triggered'},
'imperfectly':{p:'adv.',c:'不完美地',e:'in a flawed way'},
'sincerely':{p:'adv.',c:'真诚地',e:'genuinely'},
'fortitude':{p:'n.',c:'坚韧',e:'courage in adversity'},
'envisioned':{p:'v.',c:'设想',e:'imagined as possible'},
'endure':{p:'v.',c:'忍耐',e:'last; withstand'},
'deepen':{p:'v.',c:'加深',e:'become deeper'},
'void':{p:'n.',c:'空虚',e:'empty space; nothingness'},
'vast':{p:'adj.',c:'广阔的',e:'huge; immense'},
'unpredictable':{p:'adj.',c:'不可预测的',e:'not able to be predicted'},
'variables':{p:'n.',c:'变量',e:'changeable elements'},
'visible':{p:'adj.',c:'可见的',e:'able to be seen'},
'immense':{p:'adj.',c:'巨大的',e:'extremely large'},
'thresholds':{p:'n.',c:'临界值',e:'entry points; limits'},
'impersonating':{p:'v.',c:'冒充',e:'pretending to be another'},
'passive-aggressive':{p:'adj.',c:'消极攻击的',e:'indirectly resistant'},
'clear-eyed':{p:'adj.',c:'头脑清醒的',e:'mentally acute and realistic'},
'self-possession':{p:'n.',c:'沉着',e:'calmness under stress'},
'self-sabotage':{p:'n.',c:'自我破坏',e:'behavior undermining oneself'},
'production side':{p:'n.',c:'幕后',e:'behind-the-scenes process'},
'façade':{p:'n.',c:'外表',e:'false appearance concealing reality'},
}

// Merge defs into dict
for (const [w, d] of Object.entries(defs)) {
  dict[w] = d;
}
fs.writeFileSync('merged_dict.json', JSON.stringify(dict), 'utf-8');
console.log(`Dictionary with defs: ${Object.keys(dict).length} entries`);

// Generate chapter HTML
let allHTML = '';
const sortedChapters = Object.keys(chapters).map(Number).sort((a,b)=>a-b);

for (const num of sortedChapters) {
  let text = chapters[num];
  text = text.replace(/\?\?\?.*?小姐姐我真服了\?\s*/g, ' ');
  text = text.replace(/C\s+hapter/g, 'Chapter');

  const titleMatch = text.match(/^([^.!?\n]+[.!?])/);
  const title = titleMatch ? titleMatch[1].trim() : `Chapter ${num}`;
  let body = titleMatch ? text.substring(titleMatch[0].length) : text;

  allHTML += `\n<h2>Chapter ${num}: ${title}</h2>\n`;

  const sentences = body.split(/(?<=[.!?])\s+/);
  let para = '', sentCount = 0, chBold = 0;

  for (let s of sentences) {
    s = s.trim();
    if (s.length < 3) continue;

    const tokens = s.split(/\b/);
    const newTokens = [];
    for (const token of tokens) {
      const lower = token.toLowerCase();
      if (/^[a-zA-Z]{3,}$/.test(token) && masterSet.has(lower)) {
        newTokens.push(`<b>${token}</b>`);
        chBold++;
      } else {
        newTokens.push(token);
      }
    }
    s = newTokens.join('').replace(/\s{2,}/g, ' ');

    para += s + ' ';
    sentCount++;
    if (sentCount >= 4 || para.length > 500) {
      allHTML += `<p>${para.trim()}</p>\n`;
      para = ''; sentCount = 0;
    }
  }
  if (para.trim()) allHTML += `<p>${para.trim()}</p>\n`;

  console.log(`Chapter ${num}: ${chBold} bold words`);
}

console.log(`\nTotal <b>: ${(allHTML.match(/<b>/g)||[]).length}`);
fs.writeFileSync('chapters_all.html', allHTML, 'utf-8');
console.log(`chapters_all.html: ${allHTML.length} chars`);
console.log('DONE!');
